version: '3'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    
    
  db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: admin
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      volumes:
        - dbdata:/var/lib/postgresql/data
      ports:
        - 5432:5432

volumes:
  dbdata:
