# Generated by Django 5.0.2 on 2024-02-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_menuitem_is_available_menu_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='delivery_areas',
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='kitchen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_areas', to='dashboard.kitchen'),
            preserve_default=False,
        ),
    ]
