# Generated by Django 5.0.2 on 2024-02-19 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_kitchen_delivery_areas_deliveryarea_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryarea',
            name='kitchen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_area', to='dashboard.kitchen'),
        ),
    ]
